# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

softmax <- function(x) {
    .Call(`_CYBERTRACK_softmax`, x)
}

weighted_colMeans <- function(X, w, tau) {
    .Call(`_CYBERTRACK_weighted_colMeans`, X, w, tau)
}

weighted_colMeans_v2 <- function(Y, W, tau, L, D) {
    .Call(`_CYBERTRACK_weighted_colMeans_v2`, Y, W, tau, L, D)
}

mvnorm_pdf <- function(x, mean, sigma, log = TRUE) {
    .Call(`_CYBERTRACK_mvnorm_pdf`, x, mean, sigma, log)
}

mvnorm_pdf_inv <- function(x, mean, invsigma, log = TRUE) {
    .Call(`_CYBERTRACK_mvnorm_pdf_inv`, x, mean, invsigma, log)
}

mvnorm_pdf_inv_det <- function(x, mean, invsigma, rootdet, log = TRUE) {
    .Call(`_CYBERTRACK_mvnorm_pdf_inv_det`, x, mean, invsigma, rootdet, log)
}

simW <- function(Y, pi, mu, sigma, L, minmax_id, T) {
    .Call(`_CYBERTRACK_simW`, Y, pi, mu, sigma, L, minmax_id, T)
}

pi_update <- function(W, pre_pi, minmax_id, alpha, L, T) {
    .Call(`_CYBERTRACK_pi_update`, W, pre_pi, minmax_id, alpha, L, T)
}

alpha_update <- function(W, pre_alpha, pre_pi, L, minmax_id) {
    .Call(`_CYBERTRACK_alpha_update`, W, pre_alpha, pre_pi, L, minmax_id)
}

sigma_update <- function(mu, z, w, L, nu, Lambda) {
    .Call(`_CYBERTRACK_sigma_update`, mu, z, w, L, nu, Lambda)
}

sigma_update_v2 <- function(mu, Y, W, L, D, nu, Lambda) {
    .Call(`_CYBERTRACK_sigma_update_v2`, mu, Y, W, L, D, nu, Lambda)
}

rowSums <- function(X) {
    .Call(`_CYBERTRACK_rowSums`, X)
}

cybertrack <- function(Y, L, D, piini, alphaini, muini, Sigmaini, tau, nu, Lambda, num_iter, t_id) {
    .Call(`_CYBERTRACK_cybertrack`, Y, L, D, piini, alphaini, muini, Sigmaini, tau, nu, Lambda, num_iter, t_id)
}

